version: '3.1'

services:
  mysql:
    container_name: mysql_database
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: pokemons
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  mongo:
    image: mongo:7
    container_name: mongo_database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017